// SPDX-FileCopyrightText: 2026 pathetic meowmeow <uhhadd@gmail.com>
// SPDX-License-Identifier: MIT

using Robust.Shared.GameStates;

namespace Content.Shared.Body.Part;

/// <summary>
/// Marker component added to limbs that are being regenerated by the slime regeneration system.
/// This allows the shared body part system to distinguish between manual attachment and regeneration.
/// </summary>
[RegisterComponent, NetworkedComponent]
public sealed partial class RegeneratingLimbComponent : Component
{
}
