using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.MageAscension;

[GenerateTypedNameReferences]
public sealed partial class GrimoireSchoolPickerWindow : DefaultWindow
{
    public GrimoireSchoolPickerWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
