// SPDX-FileCopyrightText: 2022 Rinkashikachi <15rinkashikachi15@gmail.com>
// SPDX-FileCopyrightText: 2022 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 Rane <60792108+Elijahrane@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Fishfish458 <47410468+Fishfish458@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023-2024 Whisper <121047731+QuietlyWhisper@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Artjom <artjombebenin@gmail.com>
// SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 MilenVolf <63782763+MilenVolf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Saphire Lattice <lattice@saphi.re>
// SPDX-FileCopyrightText: 2024 goet <6637097+goet@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Thomas <87614336+Aeshus@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 KrasnoshchekovPavel <119816022+KrasnoshchekovPavel@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 TsjipTsjip <19798667+TsjipTsjip@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Rainfey <rainfey0+github@gmail.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2024 Krunklehorn <42424291+Krunklehorn@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Hannah Giovanna Dawson <karakkaraz@gmail.com>
// SPDX-FileCopyrightText: 2025 LordCarve <27449516+LordCarve@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Fruitsalad <949631+Fruitsalad@users.noreply.github.com>
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.HealthAnalyzer.UI;

public enum HealthAnalyzerMode
{
    Health,
    Integrity,
    Surgery
}

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    private NetEntity? _currentTargetEntity;
    private HealthAnalyzerMode _currentMode = HealthAnalyzerMode.Health;
    private HealthAnalyzerUiState? _currentState;
    public event Action<NetEntity>? OnBeginSurgeryClicked;

    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        
        BeginSurgeryButton.OnPressed += OnBeginSurgeryButtonPressed;
        
        // Subscribe to mode button presses
        HealthModeButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Health);
        IntegrityModeButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Integrity);
        SurgeryModeButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Surgery);
        
        // Set initial mode
        SetMode(HealthAnalyzerMode.Health);
    }

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        _currentState = msg.State;
        HealthAnalyzer.Populate(msg.State, _currentMode);
        
        // Store current target entity
        _currentTargetEntity = msg.State.TargetEntity;
        
        // Update surgery button visibility based on mode
        UpdateSurgeryButtonVisibility();
    }
    
    private void SetMode(HealthAnalyzerMode mode)
    {
        _currentMode = mode;
        
        // Update button pressed states
        HealthModeButton.Pressed = mode == HealthAnalyzerMode.Health;
        IntegrityModeButton.Pressed = mode == HealthAnalyzerMode.Integrity;
        SurgeryModeButton.Pressed = mode == HealthAnalyzerMode.Surgery;
        
        // Update UI visibility
        if (_currentState.HasValue)
        {
            HealthAnalyzer.Populate(_currentState.Value, mode);
        }
        
        // Update surgery button visibility
        UpdateSurgeryButtonVisibility();
    }
    
    private void UpdateSurgeryButtonVisibility()
    {
        // Show surgery button only in Surgery mode and when target entity is valid
        BeginSurgeryButton.Visible = _currentMode == HealthAnalyzerMode.Surgery && _currentTargetEntity != null;
    }
    
    private void OnBeginSurgeryButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (_currentTargetEntity == null)
            return;
            
        OnBeginSurgeryClicked?.Invoke(_currentTargetEntity.Value);
    }
    
    public void SetSurgeryButtonVisible(bool visible)
    {
        // Only update if we're in Surgery mode
        if (_currentMode == HealthAnalyzerMode.Surgery)
        {
            BeginSurgeryButton.Visible = visible;
        }
    }
}
