// SPDX-FileCopyrightText: 2026 Fruitsalad <949631+Fruitsalad@users.noreply.github.com>
// SPDX-License-Identifier: MIT

using System.Linq;
using System.Numerics;
using Content.Shared.Atmos;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.Medical.Surgery;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
namespace Content.Client.HealthAnalyzer.UI;

// Health analyzer UI is split from its window because it's used by both the
// health analyzer item and the cryo pod UI.

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerControl : BoxContainer
{
    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;

    private HealthAnalyzerUiState _state;
    private HealthAnalyzerMode _mode = HealthAnalyzerMode.Health;
    private NetEntity? _selectedBodyPart;
    private SurgeryLayer _selectedLayer = SurgeryLayer.Skin;

    public Action<SurgeryRequestBuiMessage>? OnSurgeryRequest;

    public HealthAnalyzerControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();

        HealthModeButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Health);
        IntegrityModeButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Integrity);
        SurgeryModeButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Surgery);
        SkinLayerButton.OnPressed += _ => SetSurgeryLayer(SurgeryLayer.Skin);
        TissueLayerButton.OnPressed += _ => SetSurgeryLayer(SurgeryLayer.Tissue);
        OrganLayerButton.OnPressed += _ => SetSurgeryLayer(SurgeryLayer.Organ);
    }

    private void SetMode(HealthAnalyzerMode mode)
    {
        _mode = mode;
        PatientDataContainer.Visible = mode == HealthAnalyzerMode.Health;
        GroupsContainer.Visible = mode == HealthAnalyzerMode.Health;
        AlertsDivider.Visible = mode == HealthAnalyzerMode.Health && (_state.Unrevivable == true || _state.Bleeding == true);
        AlertsContainer.Visible = AlertsDivider.Visible;
        IntegrityContainer.Visible = mode == HealthAnalyzerMode.Integrity;
        SurgeryContainer.Visible = mode == HealthAnalyzerMode.Surgery;
        if (mode == HealthAnalyzerMode.Integrity)
            UpdateIntegrityView();
        if (mode == HealthAnalyzerMode.Surgery)
            UpdateSurgeryView();
    }

    private void SetSurgeryLayer(SurgeryLayer layer)
    {
        _selectedLayer = layer;
        UpdateSurgeryView();
    }

    private void UpdateIntegrityView()
    {
        IntegrityLabel.Text = _state.IntegrityTotal.HasValue && _state.IntegrityMax.HasValue
            ? $"Integrity: {_state.IntegrityTotal}/{_state.IntegrityMax}"
            : "Integrity: N/A";
    }

    private void UpdateSurgeryView()
    {
        SurgeryBodyPartList.RemoveAllChildren();
        SurgeryStepsList.RemoveAllChildren();

        if (_state.TargetEntity == null || _state.BodyParts == null)
            return;

        foreach (var part in _state.BodyParts)
        {
            var btn = new Button { Text = $"Body part {part}" };
            btn.OnPressed += _ =>
            {
                _selectedBodyPart = part;
                UpdateSurgerySteps();
            };
            SurgeryBodyPartList.AddChild(btn);
        }

        if (_state.BodyParts.Count > 0 && !_selectedBodyPart.HasValue)
            _selectedBodyPart = _state.BodyParts[0];

        UpdateSurgerySteps();
    }

    private void UpdateSurgerySteps()
    {
        SurgeryStepsList.RemoveAllChildren();
        if (!_selectedBodyPart.HasValue || _state.TargetEntity == null)
            return;

        var layerState = _state.BodyPartLayerState != null
            ? _state.BodyPartLayerState.FirstOrDefault(s => s.BodyPart == _selectedBodyPart)
            : default;

        if (_selectedLayer == SurgeryLayer.Skin)
        {
            if (!layerState.SkinRetracted)
                AddStepButton("RetractSkin", "health-analyzer-surgery-step-retract-skin");
        }
        if (_selectedLayer == SurgeryLayer.Tissue)
        {
            if (!layerState.TissueRetracted && layerState.SkinRetracted)
                AddStepButton("RetractTissue", "health-analyzer-surgery-step-retract-tissue");
        }
        if (_selectedLayer == SurgeryLayer.Organ)
        {
            if (!layerState.BonesSawed && layerState.TissueRetracted)
                AddStepButton("SawBones", "health-analyzer-surgery-step-saw-bones");
        }
    }

    private void AddStepButton(string stepId, string locId)
    {
        var btn = new Button { Text = Loc.GetString(locId) };
        btn.OnPressed += _ =>
        {
            if (_state.TargetEntity == null || !_selectedBodyPart.HasValue)
                return;
            OnSurgeryRequest?.Invoke(new SurgeryRequestBuiMessage(
                _state.TargetEntity.Value,
                _selectedBodyPart.Value,
                stepId,
                _selectedLayer,
                false));
        };
        SurgeryStepsList.AddChild(btn);
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        _state = state;
        var target = _entityManager.GetEntity(state.TargetEntity);

        if (target == null
            || !_entityManager.TryGetComponent<DamageableComponent>(target, out var damageable))
        {
            NoPatientDataText.Visible = true;
            return;
        }

        NoPatientDataText.Visible = false;

        // Scan Mode

        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        ScanModeLabel.FontColorOverride = state.ScanMode.HasValue && state.ScanMode.Value ? Color.Green : Color.Red;

        // Patient Information

        SpriteView.SetEntity(target.Value);
        SpriteView.Visible = state.ScanMode.HasValue && state.ScanMode.Value;
        NoDataTex.Visible = !SpriteView.Visible;

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(_entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        NameLabel.SetMessage(name);

        SpeciesLabel.Text =
            _entityManager.TryGetComponent<HumanoidAppearanceComponent>(target.Value,
                out var humanoidAppearanceComponent)
                ? Loc.GetString(_prototypes.Index<SpeciesPrototype>(humanoidAppearanceComponent.Species).Name)
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        // Basic Diagnostic

        TemperatureLabel.Text = !float.IsNaN(state.Temperature)
            ? $"{state.Temperature - Atmospherics.T0C:F1} °C ({state.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        BloodLabel.Text = !float.IsNaN(state.BloodLevel)
            ? $"{state.BloodLevel * 100:F1} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        StatusLabel.Text =
            _entityManager.TryGetComponent<MobStateComponent>(target.Value, out var mobStateComponent)
                ? GetStatus(mobStateComponent.CurrentState)
                : Loc.GetString("health-analyzer-window-entity-unknown-text");

        // Total Damage

        DamageLabel.Text = damageable.TotalDamage.ToString();

        // Alerts

        var showAlerts = state.Unrevivable == true || state.Bleeding == true;

        AlertsDivider.Visible = showAlerts;
        AlertsContainer.Visible = showAlerts;

        if (showAlerts)
            AlertsContainer.RemoveAllChildren();

        if (state.Unrevivable == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-unrevivable-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        if (state.Bleeding == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-bleeding-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        // Damage Groups

        var damageSortedGroups =
            damageable.DamagePerGroup.OrderByDescending(damage => damage.Value)
                .ToDictionary(x => x.Key, x => x.Value);

        IReadOnlyDictionary<string, FixedPoint2> damagePerType = damageable.Damage.DamageDict;

        DrawDiagnosticGroups(damageSortedGroups, damagePerType);

        SetMode(_mode);
    }

    private static string GetStatus(MobState mobState)
    {
        return mobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
    }

    private void DrawDiagnosticGroups(
        Dictionary<string, FixedPoint2> groups,
        IReadOnlyDictionary<string, FixedPoint2> damageDict)
    {
        GroupsContainer.RemoveAllChildren();

        foreach (var (damageGroupId, damageAmount) in groups)
        {
            if (damageAmount == 0)
                continue;

            var groupTitleText = $"{Loc.GetString(
                "health-analyzer-window-damage-group-text",
                ("damageGroup", _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName),
                ("amount", damageAmount)
            )}";

            var groupContainer = new BoxContainer
            {
                Align = AlignMode.Begin,
                Orientation = LayoutOrientation.Vertical,
            };

            groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, damageGroupId));

            GroupsContainer.AddChild(groupContainer);

            // Show the damage for each type in that group.
            var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);

            foreach (var type in group.DamageTypes)
            {
                if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                    continue;

                var damageString = Loc.GetString(
                    "health-analyzer-window-damage-type-text",
                    ("damageType", _prototypes.Index<DamageTypePrototype>(type).LocalizedName),
                    ("amount", typeAmount)
                );

                groupContainer.AddChild(CreateDiagnosticItemLabel(damageString.Insert(0, " · ")));
            }
        }
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
        {
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
        }

        return _spriteSystem.Frame0(rsiSprite);
    }

    private static Label CreateDiagnosticItemLabel(string text)
    {
        return new Label
        {
            Text = text,
        };
    }

    private BoxContainer CreateDiagnosticGroupTitle(string text, string id)
    {
        var rootContainer = new BoxContainer
        {
            Margin = new Thickness(0, 6, 0, 0),
            VerticalAlignment = VAlignment.Bottom,
            Orientation = LayoutOrientation.Horizontal,
        };

        rootContainer.AddChild(new TextureRect
        {
            SetSize = new Vector2(30, 30),
            Texture = GetTexture(id.ToLower())
        });

        rootContainer.AddChild(CreateDiagnosticItemLabel(text));

        return rootContainer;
    }
}
