// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr.@gmail.com>
// SPDX-FileCopyrightText: 2023 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2025 pathetic meowmeow <uhhadd@gmail.com>
// SPDX-FileCopyrightText: 2025 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Errant <35878406+Errant-4@users.noreply.github.com>
// SPDX-License-Identifier: MIT

using System.Linq;
using Content.Shared.Hands.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Hotbar.Widgets;

[GenerateTypedNameReferences]
public sealed partial class HotbarGui : UIWidget
{
    /// <summary>
    /// When true, the leftmost hand button in the grid is the left hand (organic limbs).
    /// When false, the leftmost is the right hand (cyber limbs). Affects panel-to-hand mapping.
    /// </summary>
    private bool _leftmostHandIsLeft = true;

    public HotbarGui()
    {
        RobustXamlLoader.Load(this);
        StatusPanelRight.SetSide(HandLocation.Right);
        StatusPanelLeft.SetSide(HandLocation.Left);
        var hotbarController = UserInterfaceManager.GetUIController<HotbarUIController>();

        hotbarController.Setup(HandContainer);
        LayoutContainer.SetGrowVertical(this, LayoutContainer.GrowDirection.Begin);
    }

    /// <summary>
    /// Updates the hand-to-panel mapping based on the order of hands in the grid.
    /// Organic limbs typically have left hand first (leftmost); cyber limbs have right hand first.
    /// </summary>
    public void UpdateHandOrderMapping()
    {
        var firstButton = HandContainer.GetButtons().FirstOrDefault();
        _leftmostHandIsLeft = firstButton?.HandLocation == HandLocation.Left;
    }

    public void UpdatePanelEntityLeft(EntityUid? entity, Hand? hand)
    {
        if (_leftmostHandIsLeft)
            StatusPanelLeft.Update(entity, hand);
        else
            StatusPanelRight.Update(entity, hand);
    }

    public void UpdatePanelEntityRight(EntityUid? entity, Hand? hand)
    {
        if (_leftmostHandIsLeft)
            StatusPanelRight.Update(entity, hand);
        else
            StatusPanelLeft.Update(entity, hand);
    }

    public void SetHighlightHand(HandLocation? hand)
    {
        StatusPanelLeft.UpdateHighlight(hand is HandLocation.Left);
        StatusPanelRight.UpdateHighlight(hand is HandLocation.Right);
    }

    public void UpdateStatusVisibility(bool left, bool right)
    {
        if (_leftmostHandIsLeft)
        {
            StatusPanelLeft.Visible = left;
            StatusPanelRight.Visible = right;
        }
        else
        {
            StatusPanelLeft.Visible = right;
            StatusPanelRight.Visible = left;
        }
    }
}
